### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by poki945** [Stairdeck/scpOnlineDiscordBot#3]
Failed when getting data from server:Get https://api.scpslgame.com/lobbylist.php?format=json: x509: certificate signed by unknown authority

**Comment by Stairdeck** [comment]
I guess it's problem with network, where you launch the application?

**Comment by poki945** [comment]
Tried in the server folder

**Comment by poki945** [comment]
When I launched on my pc, it worked =/

**Comment by Stairdeck** [comment]
Cause it's network issue or something with that. If it don't work on your vps try to chat with tech support.
