### ISSUE TITLE
Please help how run on ubuntu ?

### ISSUE THREAD

**Issue by danya201272** [Stairdeck/scpOnlineDiscordBot#4]
I try to node scpbot and dont work

**Comment by Stairdeck** [comment]
It written on GoLang, not NodeJS! Just type ./scpOnlineDiscordBot

**Comment by Oyplap** [comment]
It gives me a permission denied

**Comment by Stairdeck** [comment]
> 
> 
> It gives me a permission denied

chmod 0777 scpOnlineDiscordBot

**Comment by Oyplap** [comment]
run-detectors: unable to find an interpreter for ./scpOnlineDiscordBot.exe

**Comment by Stairdeck** [comment]
> 
> 
> run-detectors: unable to find an interpreter for ./scpOnlineDiscordBot.exe

You are trying to launch windows binary in Linux? Use build for Linux system instead, it is in releases near by build for windows. It has the same name but without .exe.

**Comment by Oyplap** [comment]
How could i have missed that hahahaha.

It worked, Thank you for the quick response!
