### ISSUE TITLE
Error while getting response: Access denied

### ISSUE THREAD

**Issue by F4Fridey** [Stairdeck/scpOnlineDiscordBot#6]
I keep getting "Error while getting response: Access denied".
All info is correct in configs.
Im using the linux one.
My server is runnin gon the scopophobia beta.

**Comment by Stairdeck** [comment]
Your api key is wrong, I guess.

**Comment by F4Fridey** [comment]
Nope its correct. So is the server id, the account id and the bot token

**Comment by F4Fridey** [comment]
Download was corrupted. Re dowloaded ot and everything worked. Sorry
